name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to match the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: setup-buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    - id: login-dockerhub
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: dockerx-build-and-push
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: gat786/k8s-fastapi-sample:latest
        platforms: linux/arm64
