name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to match the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: login-dockerhub
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t gat786/k8s-fastapi-sample:latest .

    - name: Push Docker image to Docker Hub
      run: docker push gat786/k8s-fastapi-sample:latest
